S03 us03 map component
WildCodeSchool-2024-02/WildCodeSchool-2024-02-JS-Remote-JavaScrypte-P3-ElectricalScript pull request #29
Opened 2024-06-27 17:20 UTC by Pierrejuppin

Create map components with: 
   leaflet,
   leaflet-geosearch,
   leaflet.locatecontrol,
   react-leaflet
   react-leaflet-cluster

2024-06-27 19:58 UTC, BerthelotAntoine approved these changes

2024-06-27 22:27 UTC, ioayoub requested changes

2024-06-27 22:27 UTC, ioayoub commented on client/src/components/map/MapComponent.jsx
> +        const { data } = await axios.get("http://localhost:3310/api/station");
Use environment variables here, future deployement will break otherwise.

2024-06-28 07:03 UTC, HippolyteWeber approved these changes

2024-06-28 07:09 UTC, BerthelotAntoine approved these changes

2024-06-28 07:13 UTC, RiZainou approved these changes

2024-06-28 07:14 UTC, elhayanich approved these changes

2024-06-28 08:46 UTC, merged