fix: responsiv of landingpage and add typewriter effect
WildCodeSchool-2024-02/WildCodeSchool-2024-02-JS-Remote-JavaScrypte-P3-ElectricalScript pull request #44
Opened 2024-07-15 15:05 UTC by RiZainou

2024-07-15 15:19 UTC, elhayanich approved these changes

2024-07-15 15:26 UTC, BerthelotAntoine approved these changes

2024-07-15 19:20 UTC, Pierrejuppin approved these changes

2024-07-16 07:11 UTC, HippolyteWeber approved these changes

2024-07-16 16:31 UTC, ioayoub requested changes
Fix your eslint first

2024-07-22 08:03 UTC, ioayoub approved these changes

2024-07-22 08:04 UTC, ioayoub commented
Linter issue

2024-07-22 09:11 UTC, closed without merging